### ISSUE TITLE
Async fails when using java

### ISSUE THREAD

**Issue by psoares** [fnproject/tutorials#67]
I tried to follow the tutorial for Async using java instead of Go.
When I call it, I get the expected response back. e.g.: `{"call_id":"01CC4G0RVMNG8G00GZJ0000004"}`

However, the logs still show a timeout status:

```
time="2018-04-27T21:26:51Z" level=info msg="starting call" app_id=01CC4FFHN2NG8G00GZJ0000001 container_id=01CC4G0SADNG8G00GZJ0000005 id=01CC4G0RVMNG8G00GZJ0000004 route=/sleeper
time="2018-04-27T21:27:20Z" level=error msg="error running async call" error="Timed out" id=01CC4G0RVMNG8G00GZJ0000004
time="2018-04-27T21:27:20Z" level=info msg="hot function terminating" app_id=01CC4FFHN2NG8G00GZJ0000001 cpus= error="context deadline exceeded" format=http id=01CC4G0SADNG8G00GZJ0000005 idle_timeout=30 image="sleeper:0.0.7" memory=128 route=/sleeper
time="2018-04-27T21:27:20Z" level=info msg="hot function terminated" app_id=01CC4FFHN2NG8G00GZJ0000001 cpus= error="context canceled" format=http id=01CC4G0SADNG8G00GZJ0000005 idle_timeout=30 image="sleeper:0.0.7" memory=128 route=/sleeper
```
My func.yaml is:
```yaml
name: sleeper
version: 0.0.7
runtime: java
cmd: com.example.fn.HelloFunction::handleRequest
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.59
run_image: fnproject/fn-java-fdk:jdk9-1.0.59
type: async
format: http
```

My function code is:
```java
package com.example.fn;

public class HelloFunction {

    public String handleRequest(String input) throws java.lang.InterruptedException {
        String name = (input == null || input.isEmpty()) ? "world"  : input;
        Thread.sleep(120000);
        return "Hello, " + name + "!";
    }

}
```
